// Mocks generated by Mockito 5.4.4 from annotations
// in flauncher/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:typed_data' as _i11;
import 'dart:ui' as _i13;

import 'package:drift/drift.dart' as _i5;
import 'package:drift/src/runtime/executor/stream_queries.dart' as _i7;
import 'package:flauncher/database.dart' as _i6;
import 'package:flauncher/flauncher_channel.dart' as _i2;
import 'package:flauncher/gradients.dart' as _i3;
import 'package:flauncher/models/app.dart' as _i15;
import 'package:flauncher/models/category.dart' as _i16;
import 'package:flauncher/models/weather.dart' as _i20;
import 'package:flauncher/providers/apps_service.dart' as _i14;
import 'package:flauncher/providers/memory_service.dart' as _i21;
import 'package:flauncher/providers/settings_service.dart' as _i17;
import 'package:flauncher/providers/update_service.dart' as _i22;
import 'package:flauncher/providers/wallpaper_service.dart' as _i12;
import 'package:flauncher/providers/weather_service.dart' as _i19;
import 'package:flutter/cupertino.dart' as _i9;
import 'package:flutter/services.dart' as _i10;
import 'package:image_picker/image_picker.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i18;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMemoryInfo_0 extends _i1.SmartFake implements _i2.MemoryInfo {
  _FakeMemoryInfo_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCleanMemoryResult_1 extends _i1.SmartFake
    implements _i2.CleanMemoryResult {
  _FakeCleanMemoryResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFLauncherGradient_2 extends _i1.SmartFake
    implements _i3.FLauncherGradient {
  _FakeFLauncherGradient_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLostDataResponse_3 extends _i1.SmartFake
    implements _i4.LostDataResponse {
  _FakeLostDataResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMigrationStrategy_4 extends _i1.SmartFake
    implements _i5.MigrationStrategy {
  _FakeMigrationStrategy_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$AppsTable_5 extends _i1.SmartFake implements _i6.$AppsTable {
  _Fake$AppsTable_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$CategoriesTable_6 extends _i1.SmartFake
    implements _i6.$CategoriesTable {
  _Fake$CategoriesTable_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$AppsCategoriesTable_7 extends _i1.SmartFake
    implements _i6.$AppsCategoriesTable {
  _Fake$AppsCategoriesTable_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$LauncherSpacersTable_8 extends _i1.SmartFake
    implements _i6.$LauncherSpacersTable {
  _Fake$LauncherSpacersTable_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$FLauncherDatabaseManager_9 extends _i1.SmartFake
    implements _i6.$FLauncherDatabaseManager {
  _Fake$FLauncherDatabaseManager_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamQueryUpdateRules_10 extends _i1.SmartFake
    implements _i5.StreamQueryUpdateRules {
  _FakeStreamQueryUpdateRules_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGeneratedDatabase_11 extends _i1.SmartFake
    implements _i5.GeneratedDatabase {
  _FakeGeneratedDatabase_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDriftDatabaseOptions_12 extends _i1.SmartFake
    implements _i5.DriftDatabaseOptions {
  _FakeDriftDatabaseOptions_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabaseConnection_13 extends _i1.SmartFake
    implements _i5.DatabaseConnection {
  _FakeDatabaseConnection_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQueryExecutor_14 extends _i1.SmartFake implements _i5.QueryExecutor {
  _FakeQueryExecutor_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamQueryStore_15 extends _i1.SmartFake
    implements _i7.StreamQueryStore {
  _FakeStreamQueryStore_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabaseConnectionUser_16 extends _i1.SmartFake
    implements _i5.DatabaseConnectionUser {
  _FakeDatabaseConnectionUser_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMigrator_17 extends _i1.SmartFake implements _i5.Migrator {
  _FakeMigrator_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_18<T1> extends _i1.SmartFake implements _i8.Future<T1> {
  _FakeFuture_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInsertStatement_19<T1 extends _i5.Table, D1> extends _i1.SmartFake
    implements _i5.InsertStatement<T1, D1> {
  _FakeInsertStatement_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUpdateStatement_20<T extends _i5.Table, D> extends _i1.SmartFake
    implements _i5.UpdateStatement<T, D> {
  _FakeUpdateStatement_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSimpleSelectStatement_21<T1 extends _i5.HasResultSet, D>
    extends _i1.SmartFake implements _i5.SimpleSelectStatement<T1, D> {
  _FakeSimpleSelectStatement_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeJoinedSelectStatement_22<FirstT extends _i5.HasResultSet, FirstD>
    extends _i1.SmartFake implements _i5.JoinedSelectStatement<FirstT, FirstD> {
  _FakeJoinedSelectStatement_22(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSelectable_23<T> extends _i1.SmartFake implements _i5.Selectable<T> {
  _FakeSelectable_23(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeleteStatement_24<T1 extends _i5.Table, D1> extends _i1.SmartFake
    implements _i5.DeleteStatement<T1, D1> {
  _FakeDeleteStatement_24(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGenerationContext_25 extends _i1.SmartFake
    implements _i5.GenerationContext {
  _FakeGenerationContext_25(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeImageStream_26 extends _i1.SmartFake implements _i9.ImageStream {
  _FakeImageStream_26(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString(
          {_i10.DiagnosticLevel? minLevel = _i10.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeImageStreamCompleter_27 extends _i1.SmartFake
    implements _i9.ImageStreamCompleter {
  _FakeImageStreamCompleter_27(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString(
          {_i10.DiagnosticLevel? minLevel = _i10.DiagnosticLevel.info}) =>
      super.toString();
}

/// A class which mocks [FLauncherChannel].
///
/// See the documentation for Mockito's code generation for more information.
class MockFLauncherChannel extends _i1.Mock implements _i2.FLauncherChannel {
  MockFLauncherChannel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<List<Map<dynamic, dynamic>>> getApplications() =>
      (super.noSuchMethod(
        Invocation.method(
          #getApplications,
          [],
        ),
        returnValue: _i8.Future<List<Map<dynamic, dynamic>>>.value(
            <Map<dynamic, dynamic>>[]),
      ) as _i8.Future<List<Map<dynamic, dynamic>>>);

  @override
  _i8.Future<_i11.Uint8List> getApplicationBanner(String? packageName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getApplicationBanner,
          [packageName],
        ),
        returnValue: _i8.Future<_i11.Uint8List>.value(_i11.Uint8List(0)),
      ) as _i8.Future<_i11.Uint8List>);

  @override
  _i8.Future<_i11.Uint8List> getApplicationIcon(String? packageName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getApplicationIcon,
          [packageName],
        ),
        returnValue: _i8.Future<_i11.Uint8List>.value(_i11.Uint8List(0)),
      ) as _i8.Future<_i11.Uint8List>);

  @override
  _i8.Future<bool> applicationExists(String? packageName) =>
      (super.noSuchMethod(
        Invocation.method(
          #applicationExists,
          [packageName],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<void> launchActivityFromAction(String? action) =>
      (super.noSuchMethod(
        Invocation.method(
          #launchActivityFromAction,
          [action],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> launchApp(String? packageName) => (super.noSuchMethod(
        Invocation.method(
          #launchApp,
          [packageName],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> openSettings() => (super.noSuchMethod(
        Invocation.method(
          #openSettings,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> openAppInfo(String? packageName) => (super.noSuchMethod(
        Invocation.method(
          #openAppInfo,
          [packageName],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> uninstallApp(String? packageName) => (super.noSuchMethod(
        Invocation.method(
          #uninstallApp,
          [packageName],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<bool> isDefaultLauncher() => (super.noSuchMethod(
        Invocation.method(
          #isDefaultLauncher,
          [],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<bool> installApk(String? path) => (super.noSuchMethod(
        Invocation.method(
          #installApk,
          [path],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<bool> canInstallPackages() => (super.noSuchMethod(
        Invocation.method(
          #canInstallPackages,
          [],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<bool> openUnknownSourcesSettings() => (super.noSuchMethod(
        Invocation.method(
          #openUnknownSourcesSettings,
          [],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<bool> checkForGetContentAvailability() => (super.noSuchMethod(
        Invocation.method(
          #checkForGetContentAvailability,
          [],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<Map<String, dynamic>> getActiveNetworkInformation() =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveNetworkInformation,
          [],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<List<String>> getSupportedAbis() => (super.noSuchMethod(
        Invocation.method(
          #getSupportedAbis,
          [],
        ),
        returnValue: _i8.Future<List<String>>.value(<String>[]),
      ) as _i8.Future<List<String>>);

  @override
  _i8.Future<_i2.MemoryInfo> getMemoryInfo() => (super.noSuchMethod(
        Invocation.method(
          #getMemoryInfo,
          [],
        ),
        returnValue: _i8.Future<_i2.MemoryInfo>.value(_FakeMemoryInfo_0(
          this,
          Invocation.method(
            #getMemoryInfo,
            [],
          ),
        )),
      ) as _i8.Future<_i2.MemoryInfo>);

  @override
  _i8.Future<_i2.CleanMemoryResult> cleanMemory() => (super.noSuchMethod(
        Invocation.method(
          #cleanMemory,
          [],
        ),
        returnValue:
            _i8.Future<_i2.CleanMemoryResult>.value(_FakeCleanMemoryResult_1(
          this,
          Invocation.method(
            #cleanMemory,
            [],
          ),
        )),
      ) as _i8.Future<_i2.CleanMemoryResult>);

  @override
  _i8.Future<void> startAmbientMode() => (super.noSuchMethod(
        Invocation.method(
          #startAmbientMode,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void addAppsChangedListener(void Function(Map<String, dynamic>)? listener) =>
      super.noSuchMethod(
        Invocation.method(
          #addAppsChangedListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addNetworkChangedListener(
          void Function(Map<String, dynamic>)? listener) =>
      super.noSuchMethod(
        Invocation.method(
          #addNetworkChangedListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [WallpaperService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWallpaperService extends _i1.Mock implements _i12.WallpaperService {
  MockWallpaperService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.FLauncherGradient get gradient => (super.noSuchMethod(
        Invocation.getter(#gradient),
        returnValue: _FakeFLauncherGradient_2(
          this,
          Invocation.getter(#gradient),
        ),
      ) as _i3.FLauncherGradient);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i8.Future<void> pickWallpaper() => (super.noSuchMethod(
        Invocation.method(
          #pickWallpaper,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setGradient(_i3.FLauncherGradient? fLauncherGradient) =>
      (super.noSuchMethod(
        Invocation.method(
          #setGradient,
          [fLauncherGradient],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AppsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppsService extends _i1.Mock implements _i14.AppsService {
  MockAppsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get initialized => (super.noSuchMethod(
        Invocation.getter(#initialized),
        returnValue: false,
      ) as bool);

  @override
  List<_i15.App> get applications => (super.noSuchMethod(
        Invocation.getter(#applications),
        returnValue: <_i15.App>[],
      ) as List<_i15.App>);

  @override
  List<_i16.LauncherSection> get launcherSections => (super.noSuchMethod(
        Invocation.getter(#launcherSections),
        returnValue: <_i16.LauncherSection>[],
      ) as List<_i16.LauncherSection>);

  @override
  bool get hasCustomSections => (super.noSuchMethod(
        Invocation.getter(#hasCustomSections),
        returnValue: false,
      ) as bool);

  @override
  List<_i16.Category> get categories => (super.noSuchMethod(
        Invocation.getter(#categories),
        returnValue: <_i16.Category>[],
      ) as List<_i16.Category>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i15.App? getApplication(String? packageName) =>
      (super.noSuchMethod(Invocation.method(
        #getApplication,
        [packageName],
      )) as _i15.App?);

  @override
  _i8.Future<void> refreshFavoritesCategoryName() => (super.noSuchMethod(
        Invocation.method(
          #refreshFavoritesCategoryName,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void sortCategory(_i16.Category? category) => super.noSuchMethod(
        Invocation.method(
          #sortCategory,
          [category],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<_i11.Uint8List> getAppBanner(String? packageName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAppBanner,
          [packageName],
        ),
        returnValue: _i8.Future<_i11.Uint8List>.value(_i11.Uint8List(0)),
      ) as _i8.Future<_i11.Uint8List>);

  @override
  _i8.Future<_i11.Uint8List> getAppIcon(String? packageName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAppIcon,
          [packageName],
        ),
        returnValue: _i8.Future<_i11.Uint8List>.value(_i11.Uint8List(0)),
      ) as _i8.Future<_i11.Uint8List>);

  @override
  _i8.Future<void> launchApp(_i15.App? app) => (super.noSuchMethod(
        Invocation.method(
          #launchApp,
          [app],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> openAppInfo(_i15.App? app) => (super.noSuchMethod(
        Invocation.method(
          #openAppInfo,
          [app],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> uninstallApp(_i15.App? app) => (super.noSuchMethod(
        Invocation.method(
          #uninstallApp,
          [app],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> openSettings() => (super.noSuchMethod(
        Invocation.method(
          #openSettings,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<bool> isDefaultLauncher() => (super.noSuchMethod(
        Invocation.method(
          #isDefaultLauncher,
          [],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<void> startAmbientMode() => (super.noSuchMethod(
        Invocation.method(
          #startAmbientMode,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> addToCategory(
    _i15.App? app,
    _i16.Category? category, {
    bool? shouldNotifyListeners = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addToCategory,
          [
            app,
            category,
          ],
          {#shouldNotifyListeners: shouldNotifyListeners},
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> removeFromCategory(
    _i15.App? application,
    _i16.Category? category,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromCategory,
          [
            application,
            category,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> saveApplicationOrderInCategory(_i16.Category? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveApplicationOrderInCategory,
          [category],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void reorderApplication(
    _i16.Category? category,
    int? oldIndex,
    int? newIndex,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #reorderApplication,
          [
            category,
            oldIndex,
            newIndex,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<int> addCategory(
    String? categoryName, {
    _i16.CategorySort? sort = _i16.CategorySort.manual,
    _i16.CategoryType? type = _i16.CategoryType.row,
    int? columnsCount = 6,
    int? rowHeight = 110,
    bool? shouldNotifyListeners = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCategory,
          [categoryName],
          {
            #sort: sort,
            #type: type,
            #columnsCount: columnsCount,
            #rowHeight: rowHeight,
            #shouldNotifyListeners: shouldNotifyListeners,
          },
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<void> updateCategory(
    int? categoryId,
    String? name,
    _i16.CategorySort? sort,
    _i16.CategoryType? type,
    int? columnsCount,
    int? rowHeight, {
    bool? shouldNotifyListeners = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCategory,
          [
            categoryId,
            name,
            sort,
            type,
            columnsCount,
            rowHeight,
          ],
          {#shouldNotifyListeners: shouldNotifyListeners},
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> addSpacer(int? height) => (super.noSuchMethod(
        Invocation.method(
          #addSpacer,
          [height],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> updateSpacerHeight(
    _i16.LauncherSpacer? spacer,
    int? height,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSpacerHeight,
          [
            spacer,
            height,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> renameCategory(
    _i16.Category? category,
    String? categoryName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #renameCategory,
          [
            category,
            categoryName,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> deleteSection(int? index) => (super.noSuchMethod(
        Invocation.method(
          #deleteSection,
          [index],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> moveSection(
    int? oldIndex,
    int? newIndex,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #moveSection,
          [
            oldIndex,
            newIndex,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> hideApplication(_i15.App? application) =>
      (super.noSuchMethod(
        Invocation.method(
          #hideApplication,
          [application],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> showApplication(_i15.App? application) =>
      (super.noSuchMethod(
        Invocation.method(
          #showApplication,
          [application],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setCategoryType(
    _i16.Category? category,
    _i16.CategoryType? type, {
    bool? shouldNotifyListeners = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCategoryType,
          [
            category,
            type,
          ],
          {#shouldNotifyListeners: shouldNotifyListeners},
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setCategorySort(
    _i16.Category? category,
    _i16.CategorySort? sort,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCategorySort,
          [
            category,
            sort,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setCategoryColumnsCount(
    _i16.Category? category,
    int? columnsCount,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCategoryColumnsCount,
          [
            category,
            columnsCount,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setCategoryRowHeight(
    _i16.Category? category,
    int? rowHeight,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCategoryRowHeight,
          [
            category,
            rowHeight,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SettingsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsService extends _i1.Mock implements _i17.SettingsService {
  MockSettingsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get appHighlightAnimationEnabled => (super.noSuchMethod(
        Invocation.getter(#appHighlightAnimationEnabled),
        returnValue: false,
      ) as bool);

  @override
  bool get appKeyClickEnabled => (super.noSuchMethod(
        Invocation.getter(#appKeyClickEnabled),
        returnValue: false,
      ) as bool);

  @override
  bool get autoHideAppBarEnabled => (super.noSuchMethod(
        Invocation.getter(#autoHideAppBarEnabled),
        returnValue: false,
      ) as bool);

  @override
  bool get showCategoryTitles => (super.noSuchMethod(
        Invocation.getter(#showCategoryTitles),
        returnValue: false,
      ) as bool);

  @override
  bool get showDateInStatusBar => (super.noSuchMethod(
        Invocation.getter(#showDateInStatusBar),
        returnValue: false,
      ) as bool);

  @override
  bool get showMemoryInStatusBar => (super.noSuchMethod(
        Invocation.getter(#showMemoryInStatusBar),
        returnValue: false,
      ) as bool);

  @override
  bool get showTimeInStatusBar => (super.noSuchMethod(
        Invocation.getter(#showTimeInStatusBar),
        returnValue: false,
      ) as bool);

  @override
  String get backButtonAction => (super.noSuchMethod(
        Invocation.getter(#backButtonAction),
        returnValue: _i18.dummyValue<String>(
          this,
          Invocation.getter(#backButtonAction),
        ),
      ) as String);

  @override
  String get dateFormat => (super.noSuchMethod(
        Invocation.getter(#dateFormat),
        returnValue: _i18.dummyValue<String>(
          this,
          Invocation.getter(#dateFormat),
        ),
      ) as String);

  @override
  String get timeFormat => (super.noSuchMethod(
        Invocation.getter(#timeFormat),
        returnValue: _i18.dummyValue<String>(
          this,
          Invocation.getter(#timeFormat),
        ),
      ) as String);

  @override
  bool get weatherEnabled => (super.noSuchMethod(
        Invocation.getter(#weatherEnabled),
        returnValue: false,
      ) as bool);

  @override
  bool get weatherAutoLocation => (super.noSuchMethod(
        Invocation.getter(#weatherAutoLocation),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i8.Future<void> set(
    String? key,
    bool? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #set,
          [
            key,
            value,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setAppHighlightAnimationEnabled(bool? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAppHighlightAnimationEnabled,
          [value],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setAppKeyClickEnabled(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setAppKeyClickEnabled,
          [value],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setAutoHideAppBarEnabled(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setAutoHideAppBarEnabled,
          [value],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setGradientUuid(String? value) => (super.noSuchMethod(
        Invocation.method(
          #setGradientUuid,
          [value],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setFavoriteCategoryId(int? value) => (super.noSuchMethod(
        Invocation.method(
          #setFavoriteCategoryId,
          [value],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setLocale(String? value) => (super.noSuchMethod(
        Invocation.method(
          #setLocale,
          [value],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setBackButtonAction(String? value) => (super.noSuchMethod(
        Invocation.method(
          #setBackButtonAction,
          [value],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setDateTimeFormat(
    String? dateFormatString,
    String? timeFormatString,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDateTimeFormat,
          [
            dateFormatString,
            timeFormatString,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setShowCategoryTitles(bool? show) => (super.noSuchMethod(
        Invocation.method(
          #setShowCategoryTitles,
          [show],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setShowDateInStatusBar(bool? show) => (super.noSuchMethod(
        Invocation.method(
          #setShowDateInStatusBar,
          [show],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setShowMemoryInStatusBar(bool? show) => (super.noSuchMethod(
        Invocation.method(
          #setShowMemoryInStatusBar,
          [show],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setShowTimeInStatusBar(bool? show) => (super.noSuchMethod(
        Invocation.method(
          #setShowTimeInStatusBar,
          [show],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setWeatherEnabled(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setWeatherEnabled,
          [value],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setWeatherAutoLocation(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setWeatherAutoLocation,
          [value],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setWeatherLocationJson(String? value) => (super.noSuchMethod(
        Invocation.method(
          #setWeatherLocationJson,
          [value],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ImagePicker].
///
/// See the documentation for Mockito's code generation for more information.
class MockImagePicker extends _i1.Mock implements _i4.ImagePicker {
  MockImagePicker() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i4.XFile?> pickImage({
    required _i4.ImageSource? source,
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    _i4.CameraDevice? preferredCameraDevice = _i4.CameraDevice.rear,
    bool? requestFullMetadata = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickImage,
          [],
          {
            #source: source,
            #maxWidth: maxWidth,
            #maxHeight: maxHeight,
            #imageQuality: imageQuality,
            #preferredCameraDevice: preferredCameraDevice,
            #requestFullMetadata: requestFullMetadata,
          },
        ),
        returnValue: _i8.Future<_i4.XFile?>.value(),
      ) as _i8.Future<_i4.XFile?>);

  @override
  _i8.Future<List<_i4.XFile>> pickMultiImage({
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    int? limit,
    bool? requestFullMetadata = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickMultiImage,
          [],
          {
            #maxWidth: maxWidth,
            #maxHeight: maxHeight,
            #imageQuality: imageQuality,
            #limit: limit,
            #requestFullMetadata: requestFullMetadata,
          },
        ),
        returnValue: _i8.Future<List<_i4.XFile>>.value(<_i4.XFile>[]),
      ) as _i8.Future<List<_i4.XFile>>);

  @override
  _i8.Future<_i4.XFile?> pickMedia({
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    bool? requestFullMetadata = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickMedia,
          [],
          {
            #maxWidth: maxWidth,
            #maxHeight: maxHeight,
            #imageQuality: imageQuality,
            #requestFullMetadata: requestFullMetadata,
          },
        ),
        returnValue: _i8.Future<_i4.XFile?>.value(),
      ) as _i8.Future<_i4.XFile?>);

  @override
  _i8.Future<List<_i4.XFile>> pickMultipleMedia({
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    int? limit,
    bool? requestFullMetadata = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickMultipleMedia,
          [],
          {
            #maxWidth: maxWidth,
            #maxHeight: maxHeight,
            #imageQuality: imageQuality,
            #limit: limit,
            #requestFullMetadata: requestFullMetadata,
          },
        ),
        returnValue: _i8.Future<List<_i4.XFile>>.value(<_i4.XFile>[]),
      ) as _i8.Future<List<_i4.XFile>>);

  @override
  _i8.Future<_i4.XFile?> pickVideo({
    required _i4.ImageSource? source,
    _i4.CameraDevice? preferredCameraDevice = _i4.CameraDevice.rear,
    Duration? maxDuration,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickVideo,
          [],
          {
            #source: source,
            #preferredCameraDevice: preferredCameraDevice,
            #maxDuration: maxDuration,
          },
        ),
        returnValue: _i8.Future<_i4.XFile?>.value(),
      ) as _i8.Future<_i4.XFile?>);

  @override
  _i8.Future<_i4.LostDataResponse> retrieveLostData() => (super.noSuchMethod(
        Invocation.method(
          #retrieveLostData,
          [],
        ),
        returnValue:
            _i8.Future<_i4.LostDataResponse>.value(_FakeLostDataResponse_3(
          this,
          Invocation.method(
            #retrieveLostData,
            [],
          ),
        )),
      ) as _i8.Future<_i4.LostDataResponse>);

  @override
  bool supportsImageSource(_i4.ImageSource? source) => (super.noSuchMethod(
        Invocation.method(
          #supportsImageSource,
          [source],
        ),
        returnValue: false,
      ) as bool);
}

/// A class which mocks [WeatherService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherService extends _i1.Mock implements _i19.WeatherService {
  MockWeatherService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get enabled => (super.noSuchMethod(
        Invocation.getter(#enabled),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i8.Future<List<_i20.WeatherLocation>> searchCities(
    String? query, {
    String? language,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchCities,
          [query],
          {#language: language},
        ),
        returnValue: _i8.Future<List<_i20.WeatherLocation>>.value(
            <_i20.WeatherLocation>[]),
      ) as _i8.Future<List<_i20.WeatherLocation>>);

  @override
  _i8.Future<void> refresh() => (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [MemoryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMemoryService extends _i1.Mock implements _i21.MemoryService {
  MockMemoryService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get totalMem => (super.noSuchMethod(
        Invocation.getter(#totalMem),
        returnValue: 0,
      ) as int);

  @override
  set totalMem(int? _totalMem) => super.noSuchMethod(
        Invocation.setter(
          #totalMem,
          _totalMem,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get availMem => (super.noSuchMethod(
        Invocation.getter(#availMem),
        returnValue: 0,
      ) as int);

  @override
  set availMem(int? _availMem) => super.noSuchMethod(
        Invocation.setter(
          #availMem,
          _availMem,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set lastFreed(int? _lastFreed) => super.noSuchMethod(
        Invocation.setter(
          #lastFreed,
          _lastFreed,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get initialized => (super.noSuchMethod(
        Invocation.getter(#initialized),
        returnValue: false,
      ) as bool);

  @override
  int get availPercent => (super.noSuchMethod(
        Invocation.getter(#availPercent),
        returnValue: 0,
      ) as int);

  @override
  bool get cleaning => (super.noSuchMethod(
        Invocation.getter(#cleaning),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<int> clean() => (super.noSuchMethod(
        Invocation.method(
          #clean,
          [],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [UpdateService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateService extends _i1.Mock implements _i22.UpdateService {
  MockUpdateService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i22.UpdateStatus get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i22.UpdateStatus.idle,
      ) as _i22.UpdateStatus);

  @override
  int get receivedBytes => (super.noSuchMethod(
        Invocation.getter(#receivedBytes),
        returnValue: 0,
      ) as int);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i8.Future<void> check() => (super.noSuchMethod(
        Invocation.method(
          #check,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> download() => (super.noSuchMethod(
        Invocation.method(
          #download,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<bool> install() => (super.noSuchMethod(
        Invocation.method(
          #install,
          [],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [FLauncherDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFLauncherDatabase extends _i1.Mock implements _i6.FLauncherDatabase {
  MockFLauncherDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get wasCreated => (super.noSuchMethod(
        Invocation.getter(#wasCreated),
        returnValue: false,
      ) as bool);

  @override
  set wasCreated(bool? _wasCreated) => super.noSuchMethod(
        Invocation.setter(
          #wasCreated,
          _wasCreated,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get schemaVersion => (super.noSuchMethod(
        Invocation.getter(#schemaVersion),
        returnValue: 0,
      ) as int);

  @override
  _i5.MigrationStrategy get migration => (super.noSuchMethod(
        Invocation.getter(#migration),
        returnValue: _FakeMigrationStrategy_4(
          this,
          Invocation.getter(#migration),
        ),
      ) as _i5.MigrationStrategy);

  @override
  _i6.$AppsTable get apps => (super.noSuchMethod(
        Invocation.getter(#apps),
        returnValue: _Fake$AppsTable_5(
          this,
          Invocation.getter(#apps),
        ),
      ) as _i6.$AppsTable);

  @override
  _i6.$CategoriesTable get categories => (super.noSuchMethod(
        Invocation.getter(#categories),
        returnValue: _Fake$CategoriesTable_6(
          this,
          Invocation.getter(#categories),
        ),
      ) as _i6.$CategoriesTable);

  @override
  _i6.$AppsCategoriesTable get appsCategories => (super.noSuchMethod(
        Invocation.getter(#appsCategories),
        returnValue: _Fake$AppsCategoriesTable_7(
          this,
          Invocation.getter(#appsCategories),
        ),
      ) as _i6.$AppsCategoriesTable);

  @override
  _i6.$LauncherSpacersTable get launcherSpacers => (super.noSuchMethod(
        Invocation.getter(#launcherSpacers),
        returnValue: _Fake$LauncherSpacersTable_8(
          this,
          Invocation.getter(#launcherSpacers),
        ),
      ) as _i6.$LauncherSpacersTable);

  @override
  _i6.$FLauncherDatabaseManager get managers => (super.noSuchMethod(
        Invocation.getter(#managers),
        returnValue: _Fake$FLauncherDatabaseManager_9(
          this,
          Invocation.getter(#managers),
        ),
      ) as _i6.$FLauncherDatabaseManager);

  @override
  Iterable<_i5.TableInfo<_i5.Table, Object?>> get allTables =>
      (super.noSuchMethod(
        Invocation.getter(#allTables),
        returnValue: <_i5.TableInfo<_i5.Table, Object?>>[],
      ) as Iterable<_i5.TableInfo<_i5.Table, Object?>>);

  @override
  List<_i5.DatabaseSchemaEntity> get allSchemaEntities => (super.noSuchMethod(
        Invocation.getter(#allSchemaEntities),
        returnValue: <_i5.DatabaseSchemaEntity>[],
      ) as List<_i5.DatabaseSchemaEntity>);

  @override
  _i5.StreamQueryUpdateRules get streamUpdateRules => (super.noSuchMethod(
        Invocation.getter(#streamUpdateRules),
        returnValue: _FakeStreamQueryUpdateRules_10(
          this,
          Invocation.getter(#streamUpdateRules),
        ),
      ) as _i5.StreamQueryUpdateRules);

  @override
  _i5.GeneratedDatabase get attachedDatabase => (super.noSuchMethod(
        Invocation.getter(#attachedDatabase),
        returnValue: _FakeGeneratedDatabase_11(
          this,
          Invocation.getter(#attachedDatabase),
        ),
      ) as _i5.GeneratedDatabase);

  @override
  _i5.DriftDatabaseOptions get options => (super.noSuchMethod(
        Invocation.getter(#options),
        returnValue: _FakeDriftDatabaseOptions_12(
          this,
          Invocation.getter(#options),
        ),
      ) as _i5.DriftDatabaseOptions);

  @override
  _i5.DatabaseConnection get connection => (super.noSuchMethod(
        Invocation.getter(#connection),
        returnValue: _FakeDatabaseConnection_13(
          this,
          Invocation.getter(#connection),
        ),
      ) as _i5.DatabaseConnection);

  @override
  _i5.SqlTypes get typeMapping => (super.noSuchMethod(
        Invocation.getter(#typeMapping),
        returnValue: _i18.dummyValue<_i5.SqlTypes>(
          this,
          Invocation.getter(#typeMapping),
        ),
      ) as _i5.SqlTypes);

  @override
  _i5.QueryExecutor get executor => (super.noSuchMethod(
        Invocation.getter(#executor),
        returnValue: _FakeQueryExecutor_14(
          this,
          Invocation.getter(#executor),
        ),
      ) as _i5.QueryExecutor);

  @override
  _i7.StreamQueryStore get streamQueries => (super.noSuchMethod(
        Invocation.getter(#streamQueries),
        returnValue: _FakeStreamQueryStore_15(
          this,
          Invocation.getter(#streamQueries),
        ),
      ) as _i7.StreamQueryStore);

  @override
  _i5.DatabaseConnectionUser get resolvedEngine => (super.noSuchMethod(
        Invocation.getter(#resolvedEngine),
        returnValue: _FakeDatabaseConnectionUser_16(
          this,
          Invocation.getter(#resolvedEngine),
        ),
      ) as _i5.DatabaseConnectionUser);

  @override
  _i8.Future<void> persistApps(Iterable<_i6.AppsCompanion>? applications) =>
      (super.noSuchMethod(
        Invocation.method(
          #persistApps,
          [applications],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> updateApp(
    String? packageName,
    _i6.AppsCompanion? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateApp,
          [
            packageName,
            value,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> deleteApps(List<String>? packageNames) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteApps,
          [packageNames],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<int> insertCategory(_i5.Insertable<_i16.Category>? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertCategory,
          [category],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<void> deleteCategory(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteCategory,
          [id],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> updateCategories(List<_i6.CategoriesCompanion>? values) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCategories,
          [values],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> updateCategory(
    int? id,
    _i6.CategoriesCompanion? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCategory,
          [
            id,
            value,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> deleteAppCategory(
    int? categoryId,
    String? packageName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAppCategory,
          [
            categoryId,
            packageName,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> insertAppsCategories(
          List<_i6.AppsCategoriesCompanion>? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertAppsCategories,
          [value],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> replaceAppsCategories(
          List<_i6.AppsCategoriesCompanion>? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceAppsCategories,
          [value],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<int> insertSpacer(_i5.Insertable<_i16.LauncherSpacer>? spacer) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertSpacer,
          [spacer],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<int> deleteSpacer(int? spacerId) => (super.noSuchMethod(
        Invocation.method(
          #deleteSpacer,
          [spacerId],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<int> updateSpacer(
    int? spacerId,
    _i5.Insertable<_i16.LauncherSpacer>? insertable,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSpacer,
          [
            spacerId,
            insertable,
          ],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<void> updateSpacers(
          Iterable<_i6.LauncherSpacersCompanion>? values) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSpacers,
          [values],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<_i16.Category>> getCategories() => (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
        ),
        returnValue: _i8.Future<List<_i16.Category>>.value(<_i16.Category>[]),
      ) as _i8.Future<List<_i16.Category>>);

  @override
  _i8.Future<List<_i16.LauncherSpacer>> getLauncherSpacers() =>
      (super.noSuchMethod(
        Invocation.method(
          #getLauncherSpacers,
          [],
        ),
        returnValue: _i8.Future<List<_i16.LauncherSpacer>>.value(
            <_i16.LauncherSpacer>[]),
      ) as _i8.Future<List<_i16.LauncherSpacer>>);

  @override
  _i8.Future<List<_i6.AppCategory>> getAppsCategories() => (super.noSuchMethod(
        Invocation.method(
          #getAppsCategories,
          [],
        ),
        returnValue:
            _i8.Future<List<_i6.AppCategory>>.value(<_i6.AppCategory>[]),
      ) as _i8.Future<List<_i6.AppCategory>>);

  @override
  _i8.Future<List<_i15.App>> getApplications() => (super.noSuchMethod(
        Invocation.method(
          #getApplications,
          [],
        ),
        returnValue: _i8.Future<List<_i15.App>>.value(<_i15.App>[]),
      ) as _i8.Future<List<_i15.App>>);

  @override
  _i8.Future<int?> nextAppCategoryOrder(int? categoryId) => (super.noSuchMethod(
        Invocation.method(
          #nextAppCategoryOrder,
          [categoryId],
        ),
        returnValue: _i8.Future<int?>.value(),
      ) as _i8.Future<int?>);

  @override
  _i5.Migrator createMigrator() => (super.noSuchMethod(
        Invocation.method(
          #createMigrator,
          [],
        ),
        returnValue: _FakeMigrator_17(
          this,
          Invocation.method(
            #createMigrator,
            [],
          ),
        ),
      ) as _i5.Migrator);

  @override
  _i8.Future<void> beforeOpen(
    _i5.QueryExecutor? executor,
    _i5.OpeningDetails? details,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #beforeOpen,
          [
            executor,
            details,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Stream<List<Map<String, Object?>>> createStream(
          _i7.QueryStreamFetcher? stmt) =>
      (super.noSuchMethod(
        Invocation.method(
          #createStream,
          [stmt],
        ),
        returnValue: _i8.Stream<List<Map<String, Object?>>>.empty(),
      ) as _i8.Stream<List<Map<String, Object?>>>);

  @override
  T alias<T, D>(
    _i5.ResultSetImplementation<T, D>? table,
    String? alias,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #alias,
          [
            table,
            alias,
          ],
        ),
        returnValue: _i18.dummyValue<T>(
          this,
          Invocation.method(
            #alias,
            [
              table,
              alias,
            ],
          ),
        ),
      ) as T);

  @override
  void markTablesUpdated(Iterable<_i5.TableInfo<_i5.Table, dynamic>>? tables) =>
      super.noSuchMethod(
        Invocation.method(
          #markTablesUpdated,
          [tables],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyUpdates(Set<_i5.TableUpdate>? updates) => super.noSuchMethod(
        Invocation.method(
          #notifyUpdates,
          [updates],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Stream<Set<_i5.TableUpdate>> tableUpdates(
          [_i5.TableUpdateQuery? query = const _i5.TableUpdateQuery.any()]) =>
      (super.noSuchMethod(
        Invocation.method(
          #tableUpdates,
          [query],
        ),
        returnValue: _i8.Stream<Set<_i5.TableUpdate>>.empty(),
      ) as _i8.Stream<Set<_i5.TableUpdate>>);

  @override
  _i8.Future<T> doWhenOpened<T>(
          _i8.FutureOr<T> Function(_i5.QueryExecutor)? fn) =>
      (super.noSuchMethod(
        Invocation.method(
          #doWhenOpened,
          [fn],
        ),
        returnValue: _i18.ifNotNull(
              _i18.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #doWhenOpened,
                  [fn],
                ),
              ),
              (T v) => _i8.Future<T>.value(v),
            ) ??
            _FakeFuture_18<T>(
              this,
              Invocation.method(
                #doWhenOpened,
                [fn],
              ),
            ),
      ) as _i8.Future<T>);

  @override
  _i5.InsertStatement<T, D> into<T extends _i5.Table, D>(
          _i5.TableInfo<T, D>? table) =>
      (super.noSuchMethod(
        Invocation.method(
          #into,
          [table],
        ),
        returnValue: _FakeInsertStatement_19<T, D>(
          this,
          Invocation.method(
            #into,
            [table],
          ),
        ),
      ) as _i5.InsertStatement<T, D>);

  @override
  _i5.UpdateStatement<Tbl, R> update<Tbl extends _i5.Table, R>(
          _i5.TableInfo<Tbl, R>? table) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [table],
        ),
        returnValue: _FakeUpdateStatement_20<Tbl, R>(
          this,
          Invocation.method(
            #update,
            [table],
          ),
        ),
      ) as _i5.UpdateStatement<Tbl, R>);

  @override
  _i5.SimpleSelectStatement<T, R> select<T extends _i5.HasResultSet, R>(
    _i5.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #select,
          [table],
          {#distinct: distinct},
        ),
        returnValue: _FakeSimpleSelectStatement_21<T, R>(
          this,
          Invocation.method(
            #select,
            [table],
            {#distinct: distinct},
          ),
        ),
      ) as _i5.SimpleSelectStatement<T, R>);

  @override
  _i5.JoinedSelectStatement<T, R> selectOnly<T extends _i5.HasResultSet, R>(
    _i5.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectOnly,
          [table],
          {#distinct: distinct},
        ),
        returnValue: _FakeJoinedSelectStatement_22<T, R>(
          this,
          Invocation.method(
            #selectOnly,
            [table],
            {#distinct: distinct},
          ),
        ),
      ) as _i5.JoinedSelectStatement<T, R>);

  @override
  _i5.Selectable<_i5.TypedResult> selectExpressions(
          Iterable<_i5.Expression<Object>>? columns) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectExpressions,
          [columns],
        ),
        returnValue: _FakeSelectable_23<_i5.TypedResult>(
          this,
          Invocation.method(
            #selectExpressions,
            [columns],
          ),
        ),
      ) as _i5.Selectable<_i5.TypedResult>);

  @override
  _i5.DeleteStatement<T, D> delete<T extends _i5.Table, D>(
          _i5.TableInfo<T, D>? table) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [table],
        ),
        returnValue: _FakeDeleteStatement_24<T, D>(
          this,
          Invocation.method(
            #delete,
            [table],
          ),
        ),
      ) as _i5.DeleteStatement<T, D>);

  @override
  _i8.Future<int> customUpdate(
    String? query, {
    List<_i5.Variable<Object>>? variables = const [],
    Set<_i5.TableInfo<_i5.Table, dynamic>>? updates,
    _i5.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customUpdate,
          [query],
          {
            #variables: variables,
            #updates: updates,
            #updateKind: updateKind,
          },
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<int> customInsert(
    String? query, {
    List<_i5.Variable<Object>>? variables = const [],
    Set<_i5.TableInfo<_i5.Table, dynamic>>? updates,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customInsert,
          [query],
          {
            #variables: variables,
            #updates: updates,
          },
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<List<_i5.QueryRow>> customWriteReturning(
    String? query, {
    List<_i5.Variable<Object>>? variables = const [],
    Set<_i5.TableInfo<_i5.Table, dynamic>>? updates,
    _i5.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customWriteReturning,
          [query],
          {
            #variables: variables,
            #updates: updates,
            #updateKind: updateKind,
          },
        ),
        returnValue: _i8.Future<List<_i5.QueryRow>>.value(<_i5.QueryRow>[]),
      ) as _i8.Future<List<_i5.QueryRow>>);

  @override
  _i5.Selectable<_i5.QueryRow> customSelect(
    String? query, {
    List<_i5.Variable<Object>>? variables = const [],
    Set<_i5.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customSelect,
          [query],
          {
            #variables: variables,
            #readsFrom: readsFrom,
          },
        ),
        returnValue: _FakeSelectable_23<_i5.QueryRow>(
          this,
          Invocation.method(
            #customSelect,
            [query],
            {
              #variables: variables,
              #readsFrom: readsFrom,
            },
          ),
        ),
      ) as _i5.Selectable<_i5.QueryRow>);

  @override
  _i5.Selectable<_i5.QueryRow> customSelectQuery(
    String? query, {
    List<_i5.Variable<Object>>? variables = const [],
    Set<_i5.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customSelectQuery,
          [query],
          {
            #variables: variables,
            #readsFrom: readsFrom,
          },
        ),
        returnValue: _FakeSelectable_23<_i5.QueryRow>(
          this,
          Invocation.method(
            #customSelectQuery,
            [query],
            {
              #variables: variables,
              #readsFrom: readsFrom,
            },
          ),
        ),
      ) as _i5.Selectable<_i5.QueryRow>);

  @override
  _i8.Future<void> customStatement(
    String? statement, [
    List<dynamic>? args,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #customStatement,
          [
            statement,
            args,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<T> transaction<T>(
    _i8.Future<T> Function()? action, {
    bool? requireNew = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #transaction,
          [action],
          {#requireNew: requireNew},
        ),
        returnValue: _i18.ifNotNull(
              _i18.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #transaction,
                  [action],
                  {#requireNew: requireNew},
                ),
              ),
              (T v) => _i8.Future<T>.value(v),
            ) ??
            _FakeFuture_18<T>(
              this,
              Invocation.method(
                #transaction,
                [action],
                {#requireNew: requireNew},
              ),
            ),
      ) as _i8.Future<T>);

  @override
  _i8.Future<T> exclusively<T>(_i8.Future<T> Function()? action) =>
      (super.noSuchMethod(
        Invocation.method(
          #exclusively,
          [action],
        ),
        returnValue: _i18.ifNotNull(
              _i18.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #exclusively,
                  [action],
                ),
              ),
              (T v) => _i8.Future<T>.value(v),
            ) ??
            _FakeFuture_18<T>(
              this,
              Invocation.method(
                #exclusively,
                [action],
              ),
            ),
      ) as _i8.Future<T>);

  @override
  _i8.Future<void> batch(_i8.FutureOr<void> Function(_i5.Batch)? runInBatch) =>
      (super.noSuchMethod(
        Invocation.method(
          #batch,
          [runInBatch],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i5.GenerationContext $write(
    _i5.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$write,
          [component],
          {
            #hasMultipleTables: hasMultipleTables,
            #startIndex: startIndex,
          },
        ),
        returnValue: _FakeGenerationContext_25(
          this,
          Invocation.method(
            #$write,
            [component],
            {
              #hasMultipleTables: hasMultipleTables,
              #startIndex: startIndex,
            },
          ),
        ),
      ) as _i5.GenerationContext);

  @override
  _i5.GenerationContext $writeInsertable(
    _i5.TableInfo<_i5.Table, dynamic>? table,
    _i5.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$writeInsertable,
          [
            table,
            insertable,
          ],
          {#startIndex: startIndex},
        ),
        returnValue: _FakeGenerationContext_25(
          this,
          Invocation.method(
            #$writeInsertable,
            [
              table,
              insertable,
            ],
            {#startIndex: startIndex},
          ),
        ),
      ) as _i5.GenerationContext);

  @override
  String $expandVar(
    int? start,
    int? amount,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #$expandVar,
          [
            start,
            amount,
          ],
        ),
        returnValue: _i18.dummyValue<String>(
          this,
          Invocation.method(
            #$expandVar,
            [
              start,
              amount,
            ],
          ),
        ),
      ) as String);
}

/// A class which mocks [ImageProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockImageProvider<T extends Object> extends _i1.Mock
    implements _i9.ImageProvider<T> {
  MockImageProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.ImageStream resolve(_i9.ImageConfiguration? configuration) =>
      (super.noSuchMethod(
        Invocation.method(
          #resolve,
          [configuration],
        ),
        returnValue: _FakeImageStream_26(
          this,
          Invocation.method(
            #resolve,
            [configuration],
          ),
        ),
      ) as _i9.ImageStream);

  @override
  _i9.ImageStream createStream(_i9.ImageConfiguration? configuration) =>
      (super.noSuchMethod(
        Invocation.method(
          #createStream,
          [configuration],
        ),
        returnValue: _FakeImageStream_26(
          this,
          Invocation.method(
            #createStream,
            [configuration],
          ),
        ),
      ) as _i9.ImageStream);

  @override
  _i8.Future<_i9.ImageCacheStatus?> obtainCacheStatus({
    required _i9.ImageConfiguration? configuration,
    _i9.ImageErrorListener? handleError,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #obtainCacheStatus,
          [],
          {
            #configuration: configuration,
            #handleError: handleError,
          },
        ),
        returnValue: _i8.Future<_i9.ImageCacheStatus?>.value(),
      ) as _i8.Future<_i9.ImageCacheStatus?>);

  @override
  void resolveStreamForKey(
    _i9.ImageConfiguration? configuration,
    _i9.ImageStream? stream,
    T? key,
    _i9.ImageErrorListener? handleError,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #resolveStreamForKey,
          [
            configuration,
            stream,
            key,
            handleError,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<bool> evict({
    _i9.ImageCache? cache,
    _i9.ImageConfiguration? configuration = _i9.ImageConfiguration.empty,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #evict,
          [],
          {
            #cache: cache,
            #configuration: configuration,
          },
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<T> obtainKey(_i9.ImageConfiguration? configuration) =>
      (super.noSuchMethod(
        Invocation.method(
          #obtainKey,
          [configuration],
        ),
        returnValue: _i18.ifNotNull(
              _i18.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #obtainKey,
                  [configuration],
                ),
              ),
              (T v) => _i8.Future<T>.value(v),
            ) ??
            _FakeFuture_18<T>(
              this,
              Invocation.method(
                #obtainKey,
                [configuration],
              ),
            ),
      ) as _i8.Future<T>);

  @override
  _i9.ImageStreamCompleter loadBuffer(
    T? key,
    _i9.DecoderBufferCallback? decode,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadBuffer,
          [
            key,
            decode,
          ],
        ),
        returnValue: _FakeImageStreamCompleter_27(
          this,
          Invocation.method(
            #loadBuffer,
            [
              key,
              decode,
            ],
          ),
        ),
      ) as _i9.ImageStreamCompleter);

  @override
  _i9.ImageStreamCompleter loadImage(
    T? key,
    _i9.ImageDecoderCallback? decode,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadImage,
          [
            key,
            decode,
          ],
        ),
        returnValue: _FakeImageStreamCompleter_27(
          this,
          Invocation.method(
            #loadImage,
            [
              key,
              decode,
            ],
          ),
        ),
      ) as _i9.ImageStreamCompleter);
}
